// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebAPITest.Entity
{
    public partial class Media
    {
        public int Id { get; set; }
        public byte[] Img { get; set; }
    }
}